service: pros

provider:
  name: aws
  runtime: python3.6
  stage: production
  timeout: 20
  environment:
    API_URL: "https://api.sigyn.io/"
    COGNITO_ID: "4l0luscskuf56rqkeh7er7lje6"
  region: eu-west-1
  memorySize: 512

functions:
  create:
    handler: create.create
    events:
      - http:
          path: /
          method: post
          timeout: 20
  get:
    handler: get.get
    events:
      - http:
          path: /{id}
          method: get
  delete:
    handler: delete.delete
    events:
      - http:
          path: /{id}
          method: delete
  update:
    handler: update.update
    events:
      - http:
          path: /{id}
          method: put
          
  confirm:
    handler: confirm.confirm
    events:
      - http:
          path: /confirm
          method: post
