version: '2'
services:

  sigyn-apache:
    image: apache-phalcon
    build:
      context: ./sigyn/
    ports:
     - "80:80"
     - "8088:8088"
    volumes:
     - ./sigyn/www/:/var/www/html
    environment:
      DATABASE_HOST: sigyn-db.cdvjopbzfq6j.eu-west-1.rds.amazonaws.com
      DATABASE_USER: dev
      DATABASE_PASS: sigyn
      DATABASE_NAME: sigyn

  sigyn-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
    environment:
      PMA_HOST: sigyn-db.cdvjopbzfq6j.eu-west-1.rds.amazonaws.com
      MYSQL_USERNAME: dev
      MYSQL_ROOT_PASSWORD: sigyn
